### ISSUE TITLE
Unable to install pre-requisites

### ISSUE THREAD

**Issue by ash-lat** [matrix-io/matrix-malos-zwave#12]
Hi

I have been trying to install pre requisites but I keep getting following error

**Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libmatrixio-malos,
E: Unable to locate package matrixio-libzwaveip,**

Also when I am building from source, the pre-reqisites give me following error

**You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libmatrixio-protos : Depends: matrixio-protobuf but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).**

I tried installing protobuf by following below link 
https://github.com/matrix-io/protocol-buffers
and it passes through without any error

Looks like either its not able to get packages from source itslef or those packages are broken

Kindly help

Thanks in Advance

**Comment by kdpatino** [comment]
Hello @ash-lat 

Did you use:
```
# Add repo and key
curl https://apt.matrix.one/doc/apt-key.gpg | sudo apt-key add -
echo "deb https://apt.matrix.one/raspbian $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/matrixlabs.list

# Update packages and install
sudo apt-get update
sudo apt-get upgrade
```

**Comment by ash-lat** [comment]
Yes I did
But I did not install malos first.
Now I did and it installed successfully

I wanted to know regarding setting up zipgateway, I will open a new post for that

Thanks for the help 
Much appreciated
