### ISSUE TITLE
"Error Connecting" ./reference_client - Unable to connect to ZIP Gateway

### ISSUE THREAD

**Issue by ash-lat** [matrix-io/matrix-malos-zwave#13]
Hi

I installed the malos-zwave and Z/IP Gateway

and believe ZIP Gateway runs properly as when I query the status
**$ systemctl status zipgateway**

I get below response
********
�� zipgateway.service - LSB: start Z/IP Gateway (zipgateway)
   Loaded: loaded (/etc/init.d/zipgateway; generated; vendor preset: enabled)
   Active: active (running) since Tue 2018-02-27 16:51:06 UTC; 20min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 449 ExecStart=/etc/init.d/zipgateway start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/zipgateway.service
           ������527 /usr/sbin/dhcp-helper -b wlan0
           ������532 /usr/local/sbin/zipgateway --

Feb 27 16:51:05 raspberrypi systemd[1]: Starting LSB: start Z/IP Gateway (zipgateway)...
Feb 27 16:51:06 raspberrypi zipgateway[449]: Starting Z/IP Gateway: zipgatewayRestarting DHCP relay agent: 
Feb 27 16:51:06 raspberrypi zipgateway[449]: .
Feb 27 16:51:06 raspberrypi systemd[1]: Started LSB: start Z/IP Gateway (zipgateway).
lines 1-13/13 (END)
********

Also I just wanted to confirm that while setting up Z/IP Gateway I left it as default 
**Serial Port : /dev/ttyAMA0. (not default)
IPv6 for gateway - fd000:aaaa::3 
IPV6 prefix for noed - fd00:bbbb::1**

Now when I try to run
**$ avahi-browse _z-wave._udp -r**

to get the Z/IP Gateway IP address and list the services
I am not getting any response.
It just gets stuck in the bash shell

And when I try to run 
**$ ./reference_client -s fd00:aaaa::3**

I keep getting error

********
PSK not configured - using default
connect: Network is unreachable
Error connecting
********

Could you please help me get pass this issue and connect to Z/IP gateway
***************************************************************************************************
Just for reference :
When I run 
**$ malos_zwave**

I get below response 
********
**************
MALOS ZWave starting
**************

You can query specific driver info using port 50000.

FLAGS_psk : 123456789012345678901234567890aa
I/O warning : failed to load external entity "ZWave_custom_cmd_classes.xml"
Could not load Command Class definitions
terminate called after throwing an instance of 'zmq::error_t'
  what():  Address already in use
********

Thanks in Advance

**Comment by kdpatino** [comment]
Hello @ash-lat ,

**Update:** 
Could you test the instructions in https://github.com/matrix-io/matrix-malos-zwave

Let me know how the things work.

Regards,

Kevin Patino

**Comment by ash-lat** [comment]
Thanks @kdpatino 

The ZIP Gateway works now, but I am facing issue while controlling devices.
After sever tries (5 clean installations) I was able to control my device only once (which means the hardware is fine), but when I restarted it stopped working again

Could you check the screenshots below 
I see an anomaly while checking for Z-wave services in network
in IPv6 instead of showing eg. fd00:aaaa::3 its showing an IPv4 IP eg. 192.168.0.104

I send the command but it does not turn on the dimmer, only once it worked when the IPv6 IP shown during checking of Zwave services showed fd00:aaaa::3

Thanks
![discovery](https://user-images.githubusercontent.com/34689758/36845977-d1de192e-1d7e-11e8-86c9-d10d9ade40a7.png)
![withip](https://user-images.githubusercontent.com/34689758/36845978-d2150344-1d7e-11e8-9df7-a46d414fc6cf.png)
![witthoutip](https://user-images.githubusercontent.com/34689758/36845979-d24e09a0-1d7e-11e8-8dc1-dbb77a022413.png)

**Comment by ash-lat** [comment]
It works now

My router did not support IPv6
Had to change the com port during ZIP setup to ethlan as I was using ssh over wlan

Thanks @kdpatino
